# Generated by Django 5.0.4 on 2024-04-09 00:39

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complemento', models.CharField(max_length=65)),
                ('logradouro', models.CharField(max_length=65)),
                ('numero', models.CharField(max_length=65)),
                ('bairro', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('razao_social', models.CharField(max_length=65, primary_key=True, serialize=False)),
                ('documento', models.CharField(max_length=18)),
                ('contato', models.CharField(max_length=100)),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=65)),
                ('dado_bancario', models.BooleanField(default=False)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Não emitida', max_length=65)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notas.cliente')),
            ],
        ),
    ]
